#
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: Auto-Rebase

on:
  schedule:
    - cron: 0 0/4 * * *
  push:
    branches:
      - master

jobs:
  build_openwrt:
    name: Build OpenWrt firmware

    runs-on: ubuntu-18.04

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Set User
        run: |
          git config --global user.name "YourWildDad"
          git config --global user.email "053700@gmail.com"

      - name: Rebase upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.0
        with:
          upstream_repository: coolsnowwolf/lede
          upstream_branch: master
          target_branch: master
          git_pull_args: --rebase
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_push_args: --force

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
